# SPDX-License-Identifier: GPL-2.0-only
# Complete BlueZ 5.87 main.conf replacement, not a drop-in fragment.
# Review and preserve any existing administrator configuration before use.
# Vanilla HyprArch leaves controller power restoration to its saved user choice.

[Policy]
AutoEnable=false
