VANHYPRARCH_ZIG_PLAYER_VERSION=v0.1.1
VANHYPRARCH_ZIG_PLAYER_ARCHITECTURE=x86_64
VANHYPRARCH_ZIG_PLAYER_ASSET=vanhyprarch-zig-player-v0.1.1-linux-x86_64.tar.gz
VANHYPRARCH_ZIG_PLAYER_SHA256=9bd759283aa823aba124c94d64b9696df670551a1d6418ca1a32194ea0b1a887
VANHYPRARCH_ZIG_PLAYER_REPOSITORY_URL=https://github.com/vanhyprarch/vanhyprarch-zig-player
VANHYPRARCH_ZIG_PLAYER_RELEASE_URL=https://github.com/vanhyprarch/vanhyprarch-zig-player/releases/tag/v0.1.1
VANHYPRARCH_ZIG_PLAYER_DOWNLOAD_URL=https://github.com/vanhyprarch/vanhyprarch-zig-player/releases/download/v0.1.1/vanhyprarch-zig-player-v0.1.1-linux-x86_64.tar.gz
VANHYPRARCH_ZIG_PLAYER_SOURCE_TAG_URL=https://github.com/vanhyprarch/vanhyprarch-zig-player/tree/v0.1.1
VANHYPRARCH_ZIG_PLAYER_SOURCE_ARCHIVE_URL=https://github.com/vanhyprarch/vanhyprarch-zig-player/archive/refs/tags/v0.1.1.tar.gz
