schema_version = 1
release_url = "https://github.com/peteonrails/voxtype/releases/tag/v1.0.1"
signing_fingerprint = "9CCF7915B750CAE8B095ED1AA3FC9F33FD209279"

[[binaries]]
id = "cpu"
label = "CPU"
version = "1.0.1"
architecture = "x86_64"
asset = "voxtype-1.0.1-linux-x86_64-avx2"
size = 18245408
sha256 = "cb3843a894ef47aca230b30bb1c45c2ef8e0d015adf2fa754d60e55123165fd0"
download_url = "https://github.com/peteonrails/voxtype/releases/download/v1.0.1/voxtype-1.0.1-linux-x86_64-avx2"
signature_asset = "voxtype-1.0.1-linux-x86_64-avx2.asc"
signature_url = "https://github.com/peteonrails/voxtype/releases/download/v1.0.1/voxtype-1.0.1-linux-x86_64-avx2.asc"
required_cpu_features = ["avx2", "fma", "bmi1", "bmi2", "f16c", "movbe"]
ui_selectable = true

[[binaries]]
id = "vulkan"
label = "Vulkan GPU"
version = "1.0.1"
architecture = "x86_64"
asset = "voxtype-1.0.1-linux-x86_64-vulkan"
size = 64913912
sha256 = "c569d038057464aa60290296794bcbd79b928ee0efd038e33062a4c015558ed8"
download_url = "https://github.com/peteonrails/voxtype/releases/download/v1.0.1/voxtype-1.0.1-linux-x86_64-vulkan"
signature_asset = "voxtype-1.0.1-linux-x86_64-vulkan.asc"
signature_url = "https://github.com/peteonrails/voxtype/releases/download/v1.0.1/voxtype-1.0.1-linux-x86_64-vulkan.asc"
required_cpu_features = ["avx2", "fma", "bmi1", "bmi2", "f16c", "movbe"]
ui_selectable = true
