# Vanilla HyprArch portable managed lock-screen baseline.

general {
    hide_cursor = false
}

background {
    monitor =
    color = rgb(1e1e2e)
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    inner_color = rgb(11111b)
    outer_color = rgb(89b4fa)
    font_color = rgb(cdd6f4)
    fade_on_empty = false
    placeholder_text = Password
    position = 0, 0
    halign = center
    valign = center
}
